---
name: Setup Steampipe
description: >
  Setup a Steampipe environment by installing Steampipe and adding it to the PATH. Optionally install plugins and create plugin connection configurations.
author: François de Metz and Turbot
branding:
  color: red
  icon: database
inputs:
  steampipe-version:
    description: 'Steampipe CLI version to install. Defaults to "latest". Examples: latest, 0.19.4, 0.20.5.'
    default: latest
    required: false
  plugin-connections:
    description: Steampipe plugin connections to create. Accepts HCL or JSON format.
    required: false
  steampipe-plugins:
    description: The plugins to install and configure.
    required: false
outputs:
  steampipe-version:
    description: The version of Steampipe that was installed.
runs:
  using: node16
  main: dist/index.js
